# List of training manifests with sampling weights
- manifest: /abs/path/to/train_cuts.jsonl.gz
  hours: 100.0
  weights: 1

- manifest: /abs/path/to/train_cuts2.jsonl.gz
  hours: 200.0
  weights: 1

