# Training data configuration
# Each entry should have:
#   - name: dataset name for logging
#   - manifest: path to lhotse cuts manifest (jsonl or jsonl.gz)
#   - hours: approximate hours for logging/weighting
#   - weights: optional, repetition weight for training (default: 1)

# # Example:
# ----------------------voxceleb2---------------------------
- hours: 2026
  manifest: manifests/VoxCeleb2_train_pseudo_age_emotion.jsonl.gz
  weights: 1

# ----------------------CREMA---------------------------
- hours: 4.8
  manifest: manifests_norm/CREMA_train.jsonl.gz
  weights: 100

# ----------------------TESS---------------------------
- hours: 1.5
  manifest: manifests_norm/TESS_train.jsonl.gz
  weights: 100

# ----------------------RAVDESS---------------------------
- hours: 1.3
  manifest: manifests/RAVDESS_train_pseudo_age.jsonl.gz
  weights: 10

# # ----------------------IEMOCAP---------------------------
- hours: 12.5
  manifest: manifests/IEMOCAP_train_pseudo_age.jsonl.gz
  weights: 10
