# Validation data configuration
# Each entry should have:
#   - name: dataset name for logging
#   - manifest: path to lhotse cuts manifest (jsonl or jsonl.gz)


# # Validation sets prefer using the dataset with all real labels
# ----------------------CREMA---------------------------
- name: CREMA-valid
  manifest: manifests/CREMA_valid.jsonl.gz

# ----------------------TESS---------------------------
- name: TESS-valid
  manifest: manifests/TESS_valid.jsonl.gz



# # ----------------------RAVDESS--------------------------- some pseudo labels
# - name: RAVDESS-valid
#   manifest: manifests/RAVDESS_valid_pseudo_age.jsonl.gz


# # ----------------------voxceleb2--------------------------- some pseudo labels
# - name: Vox2-valid
#   manifest: manifests/VoxCeleb2_valid_pseudo_age_emotion.jsonl.gz

