exp_dir:

checkpoint:
  filename: null  # set to absolute path if you have a specific checkpoint
  epoch: 10  # which epoch to average from (used when filename is null)
  iter: 0  # which iteration to average from (used when filename is null)
  avg: 5  # how many checkpoints to average

data:
  test_data_config: configs/data_configs/valid_data_config.yaml
  sampling_rate: 16000
  max_duration: 1600
  num_workers: 8

