exp_dir:
checkpoint:
  # [Checkpoint Loading Priority]
  # 1. If 'checkpoint_filename' is provided, load directly from: {exp_dir}/{pretrained_model}
  # 2. Else if 'iter' > 0, load from: {exp_dir}/averaged_iter{iter}_avg{avg}.pt if exists else do model averaging from checkpoint-xxx.pt
  # 3. Else if 'epoch' > 0, load from: {exp_dir}/averaged_epoch{epoch}_avg{avg}.pt if exists else do model averaging from epoch-xxx.pt
  # 4. If nothing is given, load from: {exp_dir}/pretrained.pt
  filename: null      # e.g., "pretrained.pt"
  iter: 0                   # e.g., 120
  epoch: 0                  # e.g., 30
  avg: 0                    # how many checkpoints to average
multi_caption_eval: False

data:
  test_data_config:
  max_duration: 2000
  num_workers: 8