- manifest: configs/manifests/sit_ssp/aishell1.jsonl.gz
  hours: 150
  lang: zh
  weights: 0.5
- manifest: configs/manifests/sift_ssp/aishell1.jsonl.gz
  hours: 150
  lang: zh
  weights: 0.5
- manifest: configs/manifests/sift_s/aishell1.jsonl.gz
  hours: 150
  lang: zh
  weights: 0.5

- manifest: configs/manifests/sit_ssp/cs_dialogue.jsonl.gz
  hours: 103
  lang: zh
- manifest: configs/manifests/sift_ssp/cs_dialogue.jsonl.gz
  hours: 103
  lang: zh
- manifest: configs/manifests/sift_s/cs_dialogue.jsonl.gz
  hours: 103
  lang: zh

- manifest: configs/manifests/sit_ssp/emotiontalk.jsonl.gz
  hours: 23
  lang: zh
- manifest: configs/manifests/sift_ssp/emotiontalk.jsonl.gz
  hours: 23
  lang: zh
- manifest: configs/manifests/sift_s/emotiontalk.jsonl.gz
  hours: 23
  lang: zh

- manifest: configs/manifests/sit_ssp/dailytalk.jsonl.gz
  hours: 21
  lang: en
- manifest: configs/manifests/sift_ssp/dailytalk.jsonl.gz
  hours: 21
  lang: en
- manifest: configs/manifests/sift_s/dailytalk.jsonl.gz
  hours: 21
  lang: en

- manifest: configs/manifests/sit_ssp/commonvoice_en.jsonl.gz
  hours: 1199
  lang: en
  weights: 0.05
- manifest:  configs/manifests/sift_ssp/commonvoice_en.jsonl.gz
  hours: 1199
  lang: en
  weights: 0.05
- manifest: configs/manifests/sift_s/commonvoice_en.jsonl.gz
  hours: 1199
  lang: en
  weights: 0.05

- manifest: configs/manifests/sit_ssp/crema.jsonl.gz
  hours: 4.8
  lang: en
- manifest: configs/manifests/sift_ssp/crema.jsonl.gz
  hours: 4.8
  lang: en
- manifest: configs/manifests/sift_s/crema.jsonl.gz
  hours: 4.8
  lang: en

- manifest: configs/manifests/sit_ssp/iemocap.jsonl.gz
  hours: 9
  lang: en
  weights: 2
- manifest: configs/manifests/sift_ssp/iemocap.jsonl.gz
  hours: 9
  lang: en
  weights: 2
- manifest: configs/manifests/sift_s/iemocap.jsonl.gz
  hours: 9
  lang: en
  weights: 2

- manifest: configs/manifests/sit_ssp/meld.jsonl.gz
  hours: 8
  lang: en
  weights: 2
- manifest: configs/manifests/sift_ssp/meld.jsonl.gz
  hours: 8
  lang: en
  weights: 2
- manifest: configs/manifests/sift_s/meld.jsonl.gz
  hours: 8
  lang: en
  weights: 2

- manifest: configs/manifests/sit_ssp/ravdess.jsonl.gz
  hours: 1.3
  lang: en
- manifest: configs/manifests/sift_ssp/ravdess.jsonl.gz
  hours: 1.3
  lang: en
- manifest: configs/manifests/sift_s/ravdess.jsonl.gz
  hours: 1.3
  lang: en

- manifest: configs/manifests/sit_ssp/tess.jsonl.gz
  hours: 1.5
  lang: en
- manifest: configs/manifests/sift_ssp/tess.jsonl.gz
  hours: 1.5
  lang: en
- manifest: configs/manifests/sift_s/tess.jsonl.gz
  hours: 1.5
  lang: en

- manifest: configs/manifests/sit_ssp/voxceleb2.jsonl.gz
  hours: 2026
  lang: en  # actually not all english
  weights: 0.02
- manifest: configs/manifests/sift_ssp/voxceleb2.jsonl.gz
  hours: 2026
  lang: en
  weights: 0.02
- manifest: configs/manifests/sift_s/voxceleb2.jsonl.gz
  hours: 2026
  weights: 0.02
  lang: en
