
- manifest: configs/manifests/sift_s/scaled_up/wenetspeech.jsonl.gz
  hours: 9685
  lang: zh
  name: wenetspeech
- manifest: configs/manifests/sift_s/scaled_up/gigaspeech.jsonl.gz
  hours: 9396
  lang: en
  name: gigaspeech
- manifest: configs/manifests/sift_s/scaled_up/commonvoice_zh.jsonl.gz
  hours: 100
  lang: zh
  name: commonvoice_zh
- manifest: configs/manifests/sift_s/scaled_up/commonvoice_en.jsonl.gz
  hours: 1778
  lang: en
  name: commonvoice_en
- manifest: configs/manifests/sift_s/scaled_up/commonvoice_ja.jsonl.gz
  lang: ja
  hours: 19
  name: commonvoice_ja
- manifest: configs/manifests/sift_s/scaled_up/commonvoice_ko.jsonl.gz
  lang: ko
  hours: 1
  name: commonvoice_ko
- manifest: configs/manifests/sift_s/scaled_up/commonvoice_ru.jsonl.gz
  lang: ru
  hours: 37
  name: commonvoice_ru
- manifest: configs/manifests/sift_s/scaled_up/commonvoice_vi.jsonl.gz
  lang: vi
  hours: 2
  name: commonvoice_vi
- manifest: configs/manifests/sift_s/scaled_up/commonvoice_id.jsonl.gz
  lang: id
  hours: 7
  name: commonvoice_id
- manifest: configs/manifests/sift_s/scaled_up/commonvoice_fr.jsonl.gz
  lang: fr
  hours: 831
  name: commonvoice_fr
- manifest: configs/manifests/sift_s/scaled_up/commonvoice_es.jsonl.gz
  lang: es
  hours: 502
  name: commonvoice_es
- manifest: configs/manifests/sift_s/scaled_up/commonvoice_pt.jsonl.gz
  lang: pt
  hours: 25
  name: commonvoice_pt
